import CalendarEvent from "./classCalendarEvent";
import dateUtils from "./dateUtils";

function getDate(offsetDays) {
  const date = dateUtils.addDays(new Date(), offsetDays);
  return dateUtils.dateToString(date);
}

const mockEvents = [
  {
    UID: "allDay-mockEvent-1",
    date: getDate(53),
    timeStart: "00:00",
    timeEnd: "01:00",
    title: "Jamie's Birthday",
    description: "Don't forget to send a message!",
  },
  {
    UID: "allDay-mockEvent-2",
    date: getDate(65),
    timeStart: "00:00",
    timeEnd: "01:00",
    title: "Spring Break",
    description: "No classes this week.",
  },
  {
    UID: "allDay-mockEvent-3",
    date: getDate(70),
    timeStart: "00:00",
    timeEnd: "01:00",
    title: "Mom's Birthday",
    description: "Call home and wish her a happy birthday.",
  },
  {
    UID: "allDay-mockEvent-4",
    date: getDate(62),
    timeStart: "00:00",
    timeEnd: "01:00",
    title: "Roommate Move-In Day",
    description: "Help the new roommate get settled.",
  },
  {
    UID: "mockEvent-1",
    date: getDate(0),
    timeStart: "23:30",
    timeEnd: "23:45",
    title: "HIST 205 Essay due",
    description: "2,000 word analytical essay. Email to prof by midnight.",
    color: "#E24B4A",
  },
  {
    UID: "mockEvent-2",
    date: getDate(0),
    timeStart: "17:30",
    timeEnd: "18:30",
    title: "Gym — upper body",
    description: "Bench, rows, shoulder press. Don't skip the warm-up.",
    color: "#FF8C00",
  },
  {
    UID: "mockEvent-3",
    date: getDate(2),
    timeStart: "09:00",
    timeEnd: "10:30",
    title: "MATH 241 Midterm",
    description: "Chapters 12–14. Bring a pencil and your student ID.",
    color: "#E24B4A",
  },
  {
    UID: "mockEvent-4",
    date: getDate(2),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-5",
    date: getDate(2),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-6",
    date: getDate(2),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-7",
    date: getDate(2),
    timeStart: "10:00",
    timeEnd: "11:00",
    title: "PSYC 101 — Intro Psychology",
    description: "Lecture: Cognitive biases and heuristics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-8",
    date: getDate(4),
    timeStart: "19:00",
    timeEnd: "21:00",
    title: "Study session — Algorithms",
    description:
      "Work through practice problems for the upcoming midterm. Focus on greedy vs DP.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-9",
    date: getDate(4),
    timeStart: "18:00",
    timeEnd: "20:00",
    title: "Study group — Organic Chem",
    description:
      "Group review with Priya and Marcus. Cover reaction mechanisms.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-10",
    date: getDate(5),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-11",
    date: getDate(5),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-12",
    date: getDate(5),
    timeStart: "10:00",
    timeEnd: "11:00",
    title: "PSYC 101 — Intro Psychology",
    description: "Lecture: Cognitive biases and heuristics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-13",
    date: getDate(8),
    timeStart: "13:00",
    timeEnd: "15:30",
    title: "CHEM 112 Lab",
    description: "Lab: Fischer esterification. Wear goggles the whole time.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-14",
    date: getDate(8),
    timeStart: "15:00",
    timeEnd: "16:30",
    title: "CS 301 Lab",
    description:
      "Lab: implement Dijkstra's algorithm on the campus graph dataset.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-15",
    date: getDate(9),
    timeStart: "19:00",
    timeEnd: "21:00",
    title: "Study session — Algorithms",
    description:
      "Work through practice problems for the upcoming midterm. Focus on greedy vs DP.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-16",
    date: getDate(9),
    timeStart: "16:00",
    timeEnd: "18:00",
    title: "Problem set — MATH 241",
    description:
      "HW 7, problems 1–12. Double-check integration by parts section.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-17",
    date: getDate(9),
    timeStart: "13:00",
    timeEnd: "15:30",
    title: "CHEM 112 Lab",
    description: "Lab: Fischer esterification. Wear goggles the whole time.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-18",
    date: getDate(9),
    timeStart: "20:00",
    timeEnd: "22:00",
    title: "Essay draft — ENG 210",
    description: "First draft of the technical brief. Target: 1,500 words.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-19",
    date: getDate(9),
    timeStart: "21:00",
    timeEnd: "22:00",
    title: "Review lecture notes",
    description:
      "Consolidate notes from the week's lectures before the weekend.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-20",
    date: getDate(11),
    timeStart: "23:30",
    timeEnd: "23:45",
    title: "CS 301 Project due",
    description:
      "Submit the graph traversal project on Gradescope before midnight.",
    color: "#E24B4A",
  },
  {
    UID: "mockEvent-21",
    date: getDate(13),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-22",
    date: getDate(13),
    timeStart: "20:00",
    timeEnd: "21:00",
    title: "Flash cards — PSYC terms",
    description:
      "Anki deck: 50 new cards. Get through the whole Chapter 6 set.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-23",
    date: getDate(14),
    timeStart: "18:00",
    timeEnd: "20:00",
    title: "Study group — Organic Chem",
    description:
      "Group review with Priya and Marcus. Cover reaction mechanisms.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-24",
    date: getDate(15),
    timeStart: "07:00",
    timeEnd: "07:45",
    title: "Morning run",
    description: "5K around campus. Aim for sub-27 minutes.",
    color: "#FF8C00",
  },
  {
    UID: "mockEvent-25",
    date: getDate(15),
    timeStart: "17:30",
    timeEnd: "18:30",
    title: "Gym — upper body",
    description: "Bench, rows, shoulder press. Don't skip the warm-up.",
    color: "#FF8C00",
  },
  {
    UID: "mockEvent-26",
    date: getDate(15),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-27",
    date: getDate(15),
    timeStart: "10:00",
    timeEnd: "11:00",
    title: "PSYC 101 — Intro Psychology",
    description: "Lecture: Cognitive biases and heuristics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-28",
    date: getDate(15),
    timeStart: "12:30",
    timeEnd: "13:30",
    title: "Lunch with Priya",
    description:
      "Catch up at the dining hall. She's got advice on the summer internship apps.",
    color: "#50C878",
  },
  {
    UID: "mockEvent-29",
    date: getDate(16),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-30",
    date: getDate(16),
    timeStart: "10:00",
    timeEnd: "11:00",
    title: "PSYC 101 — Intro Psychology",
    description: "Lecture: Cognitive biases and heuristics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-31",
    date: getDate(18),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-32",
    date: getDate(19),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-33",
    date: getDate(19),
    timeStart: "20:00",
    timeEnd: "22:00",
    title: "Essay draft — ENG 210",
    description: "First draft of the technical brief. Target: 1,500 words.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-34",
    date: getDate(20),
    timeStart: "18:00",
    timeEnd: "20:00",
    title: "Study group — Organic Chem",
    description:
      "Group review with Priya and Marcus. Cover reaction mechanisms.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-35",
    date: getDate(21),
    timeStart: "23:30",
    timeEnd: "23:45",
    title: "HIST 205 Essay due",
    description: "2,000 word analytical essay. Email to prof by midnight.",
    color: "#E24B4A",
  },
  {
    UID: "mockEvent-36",
    date: getDate(21),
    timeStart: "13:00",
    timeEnd: "14:15",
    title: "HIST 205 — Modern World History",
    description: "Discussion section on post-WWII geopolitics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-37",
    date: getDate(21),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-38",
    date: getDate(22),
    timeStart: "08:00",
    timeEnd: "09:00",
    title: "Yoga class",
    description: "Rec center yoga. Great for stress before finals week.",
    color: "#FF8C00",
  },
  {
    UID: "mockEvent-39",
    date: getDate(22),
    timeStart: "13:00",
    timeEnd: "14:15",
    title: "HIST 205 — Modern World History",
    description: "Discussion section on post-WWII geopolitics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-40",
    date: getDate(22),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-41",
    date: getDate(27),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-42",
    date: getDate(27),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-43",
    date: getDate(28),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-44",
    date: getDate(30),
    timeStart: "20:00",
    timeEnd: "21:00",
    title: "Flash cards — PSYC terms",
    description:
      "Anki deck: 50 new cards. Get through the whole Chapter 6 set.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-45",
    date: getDate(30),
    timeStart: "19:00",
    timeEnd: "21:00",
    title: "Study session — Algorithms",
    description:
      "Work through practice problems for the upcoming midterm. Focus on greedy vs DP.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-46",
    date: getDate(30),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-47",
    date: getDate(31),
    timeStart: "08:00",
    timeEnd: "09:30",
    title: "CHEM 112 Midterm",
    description:
      "Nomenclature through stereochemistry. Review the practice exams.",
    color: "#E24B4A",
  },
  {
    UID: "mockEvent-48",
    date: getDate(32),
    timeStart: "08:00",
    timeEnd: "09:15",
    title: "CHEM 112 — Organic Chemistry",
    description:
      "Nucleophilic substitution reactions. Pre-lab quiz due tonight.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-49",
    date: getDate(32),
    timeStart: "19:00",
    timeEnd: "21:00",
    title: "Study session — Algorithms",
    description:
      "Work through practice problems for the upcoming midterm. Focus on greedy vs DP.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-50",
    date: getDate(32),
    timeStart: "18:00",
    timeEnd: "20:00",
    title: "Study group — Organic Chem",
    description:
      "Group review with Priya and Marcus. Cover reaction mechanisms.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-51",
    date: getDate(33),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-52",
    date: getDate(33),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-53",
    date: getDate(35),
    timeStart: "18:00",
    timeEnd: "20:00",
    title: "Study group — Organic Chem",
    description:
      "Group review with Priya and Marcus. Cover reaction mechanisms.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-54",
    date: getDate(35),
    timeStart: "12:00",
    timeEnd: "12:30",
    title: "Return library books",
    description:
      "Three books due. Pick up the reserve copy of the algorithms textbook.",
    color: "#E8A838",
  },
  {
    UID: "mockEvent-55",
    date: getDate(35),
    timeStart: "07:00",
    timeEnd: "07:45",
    title: "Morning run",
    description: "5K around campus. Aim for sub-27 minutes.",
    color: "#FF8C00",
  },
  {
    UID: "mockEvent-56",
    date: getDate(36),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-57",
    date: getDate(36),
    timeStart: "13:00",
    timeEnd: "14:15",
    title: "HIST 205 — Modern World History",
    description: "Discussion section on post-WWII geopolitics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-58",
    date: getDate(36),
    timeStart: "08:00",
    timeEnd: "09:15",
    title: "CHEM 112 — Organic Chemistry",
    description:
      "Nucleophilic substitution reactions. Pre-lab quiz due tonight.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-59",
    date: getDate(36),
    timeStart: "13:00",
    timeEnd: "15:30",
    title: "CHEM 112 Lab",
    description: "Lab: Fischer esterification. Wear goggles the whole time.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-60",
    date: getDate(36),
    timeStart: "15:00",
    timeEnd: "16:30",
    title: "CS 301 Lab",
    description:
      "Lab: implement Dijkstra's algorithm on the campus graph dataset.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-61",
    date: getDate(37),
    timeStart: "20:00",
    timeEnd: "21:00",
    title: "Flash cards — PSYC terms",
    description:
      "Anki deck: 50 new cards. Get through the whole Chapter 6 set.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-62",
    date: getDate(37),
    timeStart: "19:00",
    timeEnd: "21:00",
    title: "Study session — Algorithms",
    description:
      "Work through practice problems for the upcoming midterm. Focus on greedy vs DP.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-63",
    date: getDate(38),
    timeStart: "14:00",
    timeEnd: "17:00",
    title: "Library deep work",
    description: "No phone. Finish reading for HIST 205 and outline the essay.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-64",
    date: getDate(38),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-65",
    date: getDate(38),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-66",
    date: getDate(40),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-67",
    date: getDate(40),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-68",
    date: getDate(42),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-69",
    date: getDate(42),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-70",
    date: getDate(42),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-71",
    date: getDate(43),
    timeStart: "10:00",
    timeEnd: "11:00",
    title: "PSYC 101 — Intro Psychology",
    description: "Lecture: Cognitive biases and heuristics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-72",
    date: getDate(43),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-73",
    date: getDate(44),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-74",
    date: getDate(44),
    timeStart: "17:30",
    timeEnd: "18:30",
    title: "Gym — upper body",
    description: "Bench, rows, shoulder press. Don't skip the warm-up.",
    color: "#FF8C00",
  },
  {
    UID: "mockEvent-75",
    date: getDate(47),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-76",
    date: getDate(47),
    timeStart: "10:00",
    timeEnd: "11:00",
    title: "PSYC 101 — Intro Psychology",
    description: "Lecture: Cognitive biases and heuristics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-77",
    date: getDate(47),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-78",
    date: getDate(48),
    timeStart: "20:00",
    timeEnd: "22:30",
    title: "Movie night",
    description:
      "Watching 'Everything Everywhere All at Once' at Dom's. Bring snacks.",
    color: "#50C878",
  },
  {
    UID: "mockEvent-79",
    date: getDate(48),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-80",
    date: getDate(48),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-81",
    date: getDate(48),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-82",
    date: getDate(48),
    timeStart: "19:00",
    timeEnd: "22:00",
    title: "Board game night",
    description:
      "Catan and Ticket to Ride at the common room. Bring the snack budget.",
    color: "#50C878",
  },
  {
    UID: "mockEvent-83",
    date: getDate(49),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-84",
    date: getDate(49),
    timeStart: "14:00",
    timeEnd: "14:30",
    title: "Advising appointment",
    description:
      "Check graduation requirements and plan the remaining semesters.",
    color: "#E8A838",
  },
  {
    UID: "mockEvent-85",
    date: getDate(49),
    timeStart: "17:00",
    timeEnd: "18:30",
    title: "Debate team practice",
    description: "Prep for the regional tournament. Practice rebuttals.",
    color: "#20B2AA",
  },
  {
    UID: "mockEvent-86",
    date: getDate(51),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-87",
    date: getDate(51),
    timeStart: "13:00",
    timeEnd: "14:15",
    title: "HIST 205 — Modern World History",
    description: "Discussion section on post-WWII geopolitics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-88",
    date: getDate(51),
    timeStart: "08:00",
    timeEnd: "09:15",
    title: "CHEM 112 — Organic Chemistry",
    description:
      "Nucleophilic substitution reactions. Pre-lab quiz due tonight.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-89",
    date: getDate(52),
    timeStart: "10:00",
    timeEnd: "11:00",
    title: "PSYC 101 — Intro Psychology",
    description: "Lecture: Cognitive biases and heuristics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-90",
    date: getDate(52),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-91",
    date: getDate(53),
    timeStart: "13:00",
    timeEnd: "14:15",
    title: "HIST 205 — Modern World History",
    description: "Discussion section on post-WWII geopolitics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-92",
    date: getDate(53),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-93",
    date: getDate(54),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-94",
    date: getDate(54),
    timeStart: "10:00",
    timeEnd: "11:00",
    title: "PSYC 101 — Intro Psychology",
    description: "Lecture: Cognitive biases and heuristics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-95",
    date: getDate(55),
    timeStart: "10:00",
    timeEnd: "10:30",
    title: "PSYC 101 Quiz",
    description: "In-class quiz on chapters 4–6. 20 multiple choice questions.",
    color: "#E24B4A",
  },
  {
    UID: "mockEvent-96",
    date: getDate(55),
    timeStart: "20:00",
    timeEnd: "21:00",
    title: "Flash cards — PSYC terms",
    description:
      "Anki deck: 50 new cards. Get through the whole Chapter 6 set.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-97",
    date: getDate(55),
    timeStart: "18:00",
    timeEnd: "20:00",
    title: "Study group — Organic Chem",
    description:
      "Group review with Priya and Marcus. Cover reaction mechanisms.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-98",
    date: getDate(56),
    timeStart: "23:30",
    timeEnd: "23:45",
    title: "CS 301 Project due",
    description:
      "Submit the graph traversal project on Gradescope before midnight.",
    color: "#E24B4A",
  },
  {
    UID: "mockEvent-99",
    date: getDate(56),
    timeStart: "15:00",
    timeEnd: "16:30",
    title: "CS 301 Lab",
    description:
      "Lab: implement Dijkstra's algorithm on the campus graph dataset.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-100",
    date: getDate(56),
    timeStart: "13:00",
    timeEnd: "15:30",
    title: "CHEM 112 Lab",
    description: "Lab: Fischer esterification. Wear goggles the whole time.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-101",
    date: getDate(56),
    timeStart: "10:00",
    timeEnd: "11:00",
    title: "FAFSA renewal",
    description:
      "Complete the financial aid renewal form. Have tax docs ready.",
    color: "#E8A838",
  },
  {
    UID: "mockEvent-102",
    date: getDate(56),
    timeStart: "07:00",
    timeEnd: "07:45",
    title: "Morning run",
    description: "5K around campus. Aim for sub-27 minutes.",
    color: "#FF8C00",
  },
  {
    UID: "mockEvent-103",
    date: getDate(58),
    timeStart: "19:00",
    timeEnd: "21:00",
    title: "Study session — Algorithms",
    description:
      "Work through practice problems for the upcoming midterm. Focus on greedy vs DP.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-104",
    date: getDate(58),
    timeStart: "17:30",
    timeEnd: "18:30",
    title: "Gym — upper body",
    description: "Bench, rows, shoulder press. Don't skip the warm-up.",
    color: "#FF8C00",
  },
  {
    UID: "mockEvent-105",
    date: getDate(58),
    timeStart: "12:30",
    timeEnd: "13:30",
    title: "Lunch with Priya",
    description:
      "Catch up at the dining hall. She's got advice on the summer internship apps.",
    color: "#50C878",
  },
  {
    UID: "mockEvent-106",
    date: getDate(59),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-107",
    date: getDate(60),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-108",
    date: getDate(60),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-109",
    date: getDate(62),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-110",
    date: getDate(62),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-111",
    date: getDate(62),
    timeStart: "14:00",
    timeEnd: "14:30",
    title: "Advising appointment",
    description:
      "Check graduation requirements and plan the remaining semesters.",
    color: "#E8A838",
  },
  {
    UID: "mockEvent-112",
    date: getDate(64),
    timeStart: "18:00",
    timeEnd: "20:00",
    title: "Study group — Organic Chem",
    description:
      "Group review with Priya and Marcus. Cover reaction mechanisms.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-113",
    date: getDate(64),
    timeStart: "20:00",
    timeEnd: "22:30",
    title: "Movie night",
    description:
      "Watching 'Everything Everywhere All at Once' at Dom's. Bring snacks.",
    color: "#50C878",
  },
  {
    UID: "mockEvent-114",
    date: getDate(64),
    timeStart: "20:00",
    timeEnd: "22:00",
    title: "Essay draft — ENG 210",
    description: "First draft of the technical brief. Target: 1,500 words.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-115",
    date: getDate(64),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-116",
    date: getDate(66),
    timeStart: "20:00",
    timeEnd: "22:30",
    title: "Movie night",
    description:
      "Watching 'Everything Everywhere All at Once' at Dom's. Bring snacks.",
    color: "#50C878",
  },
  {
    UID: "mockEvent-117",
    date: getDate(70),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-118",
    date: getDate(70),
    timeStart: "19:00",
    timeEnd: "21:00",
    title: "Study session — Algorithms",
    description:
      "Work through practice problems for the upcoming midterm. Focus on greedy vs DP.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-119",
    date: getDate(70),
    timeStart: "20:00",
    timeEnd: "21:00",
    title: "Flash cards — PSYC terms",
    description:
      "Anki deck: 50 new cards. Get through the whole Chapter 6 set.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-120",
    date: getDate(70),
    timeStart: "08:00",
    timeEnd: "09:15",
    title: "CHEM 112 — Organic Chemistry",
    description:
      "Nucleophilic substitution reactions. Pre-lab quiz due tonight.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-121",
    date: getDate(70),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-122",
    date: getDate(71),
    timeStart: "20:00",
    timeEnd: "21:00",
    title: "Flash cards — PSYC terms",
    description:
      "Anki deck: 50 new cards. Get through the whole Chapter 6 set.",
    color: "#7B68EE",
  },
  {
    UID: "mockEvent-123",
    date: getDate(71),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-124",
    date: getDate(75),
    timeStart: "08:00",
    timeEnd: "09:15",
    title: "CHEM 112 — Organic Chemistry",
    description:
      "Nucleophilic substitution reactions. Pre-lab quiz due tonight.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-125",
    date: getDate(75),
    timeStart: "13:00",
    timeEnd: "14:15",
    title: "HIST 205 — Modern World History",
    description: "Discussion section on post-WWII geopolitics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-126",
    date: getDate(75),
    timeStart: "17:30",
    timeEnd: "18:30",
    title: "Gym — upper body",
    description: "Bench, rows, shoulder press. Don't skip the warm-up.",
    color: "#FF8C00",
  },
  {
    UID: "mockEvent-127",
    date: getDate(75),
    timeStart: "07:00",
    timeEnd: "07:45",
    title: "Morning run",
    description: "5K around campus. Aim for sub-27 minutes.",
    color: "#FF8C00",
  },
  {
    UID: "mockEvent-128",
    date: getDate(76),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-129",
    date: getDate(77),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-130",
    date: getDate(77),
    timeStart: "17:30",
    timeEnd: "18:30",
    title: "Gym — upper body",
    description: "Bench, rows, shoulder press. Don't skip the warm-up.",
    color: "#FF8C00",
  },
  {
    UID: "mockEvent-131",
    date: getDate(77),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-132",
    date: getDate(78),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-133",
    date: getDate(78),
    timeStart: "08:00",
    timeEnd: "09:00",
    title: "Yoga class",
    description: "Rec center yoga. Great for stress before finals week.",
    color: "#FF8C00",
  },
  {
    UID: "mockEvent-134",
    date: getDate(78),
    timeStart: "09:00",
    timeEnd: "10:15",
    title: "CS 301 — Algorithms Lecture",
    description: "Lecture on dynamic programming. Read ch. 15 before class.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-135",
    date: getDate(78),
    timeStart: "13:00",
    timeEnd: "14:15",
    title: "HIST 205 — Modern World History",
    description: "Discussion section on post-WWII geopolitics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-136",
    date: getDate(78),
    timeStart: "14:00",
    timeEnd: "15:15",
    title: "ENG 210 — Technical Writing",
    description: "Peer review workshop for the memo assignment.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-137",
    date: getDate(79),
    timeStart: "15:00",
    timeEnd: "16:30",
    title: "CS 301 Lab",
    description:
      "Lab: implement Dijkstra's algorithm on the campus graph dataset.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-138",
    date: getDate(82),
    timeStart: "17:30",
    timeEnd: "18:30",
    title: "Gym — upper body",
    description: "Bench, rows, shoulder press. Don't skip the warm-up.",
    color: "#FF8C00",
  },
  {
    UID: "mockEvent-139",
    date: getDate(82),
    timeStart: "14:00",
    timeEnd: "14:30",
    title: "Advising appointment",
    description:
      "Check graduation requirements and plan the remaining semesters.",
    color: "#E8A838",
  },
  {
    UID: "mockEvent-140",
    date: getDate(82),
    timeStart: "07:00",
    timeEnd: "07:45",
    title: "Morning run",
    description: "5K around campus. Aim for sub-27 minutes.",
    color: "#FF8C00",
  },
  {
    UID: "mockEvent-141",
    date: getDate(83),
    timeStart: "10:00",
    timeEnd: "11:00",
    title: "PSYC 101 — Intro Psychology",
    description: "Lecture: Cognitive biases and heuristics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-142",
    date: getDate(83),
    timeStart: "11:00",
    timeEnd: "12:15",
    title: "MATH 241 — Calculus III",
    description: "Partial derivatives and gradient vectors. HW due Friday.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-143",
    date: getDate(89),
    timeStart: "08:00",
    timeEnd: "09:15",
    title: "CHEM 112 — Organic Chemistry",
    description:
      "Nucleophilic substitution reactions. Pre-lab quiz due tonight.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-144",
    date: getDate(89),
    timeStart: "13:00",
    timeEnd: "14:15",
    title: "HIST 205 — Modern World History",
    description: "Discussion section on post-WWII geopolitics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-145",
    date: getDate(90),
    timeStart: "13:00",
    timeEnd: "14:15",
    title: "HIST 205 — Modern World History",
    description: "Discussion section on post-WWII geopolitics.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-146",
    date: getDate(91),
    timeStart: "13:00",
    timeEnd: "15:30",
    title: "CHEM 112 Lab",
    description: "Lab: Fischer esterification. Wear goggles the whole time.",
    color: "#4A90D9",
  },
  {
    UID: "mockEvent-147",
    date: getDate(91),
    timeStart: "19:00",
    timeEnd: "21:00",
    title: "Study session — Algorithms",
    description:
      "Work through practice problems for the upcoming midterm. Focus on greedy vs DP.",
    color: "#7B68EE",
  },
];

function createMockEvents() {
  localStorage.setItem("mockEventsLoaded", "true");
  console.log("Loading mock events...");

  return mockEvents.map((props) => new CalendarEvent(props));
}

function deleteMockEvents() {
  if (localStorage.getItem("mockEventsLoaded") === "false") return;
  console.log("Deleting mock events...");

  const keys = [];
  for (let i = 0; i < localStorage.length; i++) {
    let key = localStorage.key(i);
    if (key.includes("mockEvent")) {
      keys.push(key);
    }
  }
  keys.forEach((key) => {
    localStorage.removeItem(key);
  });
  localStorage.setItem("mockEventsLoaded", "false");
}

function registerCheatCode(callback, key = "F2", times = 3, timeout = 2000) {
  let presses = 0;
  let timer = null;

  window.addEventListener("keydown", (e) => {
    if (e.key !== key) return;

    presses++;
    clearTimeout(timer);

    if (presses >= times) {
      callback();
      presses = 0;
      return;
    }

    timer = setTimeout(() => {
      presses = 0;
    }, timeout);
  });
}

export { createMockEvents, deleteMockEvents, registerCheatCode };
